# Rate limiting para Keycloak
limit_req_zone $binary_remote_addr zone=kc_login:10m rate=5r/s;
limit_req_zone $binary_remote_addr zone=kc_general:10m rate=30r/s;

server {
    listen 80;
    server_name auth.*.nip.io;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name auth.*.nip.io;

    # TLS autofirmado
    ssl_certificate /etc/letsencrypt/live/selfsigned/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/selfsigned/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305';
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    include /etc/nginx/conf.d/security-headers.conf;

    client_max_body_size 10M;

    # Rate limit en endpoint de login
    location /realms/corporativo/protocol/openid-connect/token {
        limit_req zone=kc_login burst=10 nodelay;
        limit_req_status 429;
        proxy_pass http://keycloak:8080;
        include /etc/nginx/conf.d/proxy-params.conf;
    }

    # Consola de administracion — acceso restringido
    location /admin {
        # Descomentar para restringir por IP
        # allow 1.2.3.4;
        # deny all;
        proxy_pass http://keycloak:8080;
        include /etc/nginx/conf.d/proxy-params.conf;
    }

    # General
    location / {
        limit_req zone=kc_general burst=50 nodelay;
        proxy_pass http://keycloak:8080;
        include /etc/nginx/conf.d/proxy-params.conf;
    }

    location ~ /\. { deny all; }
}
