# Fail2ban filter — Login fallido en Vaultwarden
[Definition]
failregex = ^.*Username or password is incorrect\. Try again\. IP: <ADDR>\..*$
            ^.*Invalid credentials\. IP: <ADDR>\..*$
ignoreregex =
