# PassProtect — Build de imagenes custom
# Uso: docker compose -f proyectos/docker-compose/docker-compose.build.yml build

services:
  ubbasse:
    build:
      context: ../..
      dockerfile: dockerfiles/base/Dockerfile
    image: dsegura97/ubbasse:latest

  ubseguridadd:
    build:
      context: ../..
      dockerfile: dockerfiles/seguridad/Dockerfile
    image: dsegura97/ubseguridadd:latest
    depends_on:
      - ubbasse

  vaultwarden-corp:
    build:
      context: ../..
      dockerfile: dockerfiles/vaultwarden/Dockerfile
    image: dsegura97/vaultwarden-corp:1.0.0
    depends_on:
      - ubseguridadd

  keycloak-corp:
    build:
      context: ../..
      dockerfile: dockerfiles/keycloak/Dockerfile
    image: dsegura97/keycloak-corp:1.0.0
    depends_on:
      - ubseguridadd

  mariadb-corp:
    build:
      context: ../..
      dockerfile: dockerfiles/mariadb/Dockerfile
    image: dsegura97/mariadb-corp:1.0.0
    depends_on:
      - ubseguridadd

  nginx-proxy-corp:
    build:
      context: ../..
      dockerfile: dockerfiles/nginx-proxy/Dockerfile
    image: dsegura97/nginx-proxy-corp:1.0.0
    depends_on:
      - ubseguridadd

  dashboard-corp:
    build:
      context: ../..
      dockerfile: dockerfiles/dashboard/Dockerfile
    image: dsegura97/dashboard-corp:1.0.0
    depends_on:
      - ubseguridadd
