apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: auth
type: Opaque
stringData:
  admin-password: "CAMBIAR"
  db-root-password: "CAMBIAR"
  db-password: "CAMBIAR"
---
apiVersion: v1
kind: Secret
metadata:
  name: freeipa-secrets
  namespace: auth
type: Opaque
stringData:
  ds-password: "CAMBIAR_12chars"
  admin-password: "CAMBIAR_12chars"
