# Fail2ban filter — Acceso fallido al panel de admin de Vaultwarden
[Definition]
failregex = ^.*Invalid admin token\. IP: <ADDR>\..*$
            ^.*Unauthorized request to admin panel\. IP: <ADDR>\..*$
ignoreregex =
