apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secrets
  namespace: vaultwarden
type: Opaque
stringData:
  admin-token: "CAMBIAR_openssl_rand_base64_48"
  db-root-password: "CAMBIAR"
  db-password: "CAMBIAR"
  sso-client-secret: "CAMBIAR"
