apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: auth
data:
  KC_DB: "postgres"
  KC_DB_URL: "jdbc:postgresql://postgres-kc:5432/keycloak"
  KC_DB_USERNAME: "keycloak"
  KC_HOSTNAME: "auth.passprotect.es"
  KC_PROXY: "edge"
  KC_HEALTH_ENABLED: "true"
  KC_METRICS_ENABLED: "true"
