apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: auth
type: Opaque
stringData:
  admin-password: "CAMBIAR"
  db-root-password: "CAMBIAR"
  db-password: "CAMBIAR"
---
apiVersion: v1
kind: Secret
metadata:
  name: openldap-secrets
  namespace: auth
type: Opaque
stringData:
  admin-password: "CAMBIAR_24chars"
  config-password: "CAMBIAR_24chars"
