# PassProtect — Build de imagenes custom
# Uso: docker compose -f proyectos/passprotect/docker-compose/docker-compose.build.yml build

services:
  ubbase:
    build:
      context: ../../..
      dockerfile: docker/kube/base/Dockerfile
    image: dsegura97/ubbase:latest

  ubseguridad:
    build:
      context: ../../..
      dockerfile: docker/kube/seguridad/Dockerfile
    image: dsegura97/ubseguridad:latest
    depends_on:
      - ubbase

  vaultwarden-corp:
    build:
      context: ../../..
      dockerfile: docker/kube/vaultwarden/Dockerfile
    image: dsegura97/vaultwarden-corp:1.0.0
    depends_on:
      - ubseguridad

  keycloak-corp:
    build:
      context: ../../..
      dockerfile: docker/kube/keycloak/Dockerfile
    image: dsegura97/keycloak-corp:1.0.0
    depends_on:
      - ubseguridad

  mariadb-corp:
    build:
      context: ../../..
      dockerfile: docker/kube/mariadb/Dockerfile
    image: dsegura97/mariadb-corp:1.0.0
    depends_on:
      - ubseguridad

  nginx-proxy-corp:
    build:
      context: ../../..
      dockerfile: docker/kube/nginx-proxy/Dockerfile
    image: dsegura97/nginx-proxy-corp:1.0.0
    depends_on:
      - ubseguridad
