apiVersion: v1
kind: Namespace
metadata:
  name: vaultwarden
  labels:
    {{- include "passprotect.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: auth
  labels:
    {{- include "passprotect.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    {{- include "passprotect.labels" . | nindent 4 }}
