apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data
  namespace: vaultwarden
  labels:
    {{- include "passprotect.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.vaultwarden.persistence.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-vw
  namespace: vaultwarden
  labels:
    {{- include "passprotect.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.mariadbVw.persistence.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-kc
  namespace: auth
  labels:
    {{- include "passprotect.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.mariadbKc.persistence.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freeipa-data
  namespace: auth
  labels:
    {{- include "passprotect.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.freeipa.persistence.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-storage
  namespace: monitoring
  labels:
    {{- include "passprotect.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.monitoring.backup.persistence.size }}
