apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secrets
  namespace: vaultwarden
  labels:
    {{- include "passprotect.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-token: {{ required "vaultwarden admin token requerido" .Values.vaultwarden.adminToken | quote }}
  db-root-password: {{ required "mariadb-vw root password requerido" .Values.mariadbVw.rootPassword | quote }}
  db-password: {{ required "mariadb-vw password requerido" .Values.mariadbVw.password | quote }}
  sso-client-secret: {{ required "SSO client secret requerido" .Values.vaultwarden.sso.clientSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: auth
  labels:
    {{- include "passprotect.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ required "keycloak admin password requerido" .Values.keycloak.adminPassword | quote }}
  db-root-password: {{ required "mariadb-kc root password requerido" .Values.mariadbKc.rootPassword | quote }}
  db-password: {{ required "mariadb-kc password requerido" .Values.mariadbKc.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: freeipa-secrets
  namespace: auth
  labels:
    {{- include "passprotect.labels" . | nindent 4 }}
type: Opaque
stringData:
  ds-password: {{ required "FreeIPA DS password requerido" .Values.freeipa.dsPassword | quote }}
  admin-password: {{ required "FreeIPA admin password requerido" .Values.freeipa.adminPassword | quote }}
