apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secrets
  namespace: vaultwarden
  labels:
    {{- include "passprotect.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-token: {{ required "vaultwarden admin token requerido" .Values.vaultwarden.adminToken | quote }}
  db-password: {{ required "postgres-vw password requerido" .Values.postgresVw.password | quote }}
  sso-client-secret: {{ required "SSO client secret requerido" .Values.vaultwarden.sso.clientSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: auth
  labels:
    {{- include "passprotect.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ required "keycloak admin password requerido" .Values.keycloak.adminPassword | quote }}
  db-password: {{ required "postgres-kc password requerido" .Values.postgresKc.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: openldap-secrets
  namespace: auth
  labels:
    {{- include "passprotect.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ required "OpenLDAP admin password requerido" .Values.openldap.adminPassword | quote }}
  config-password: {{ required "OpenLDAP config password requerido" .Values.openldap.configPassword | quote }}
